server:
  port: 8762
spring:
  application:
      name: interest-zipkin
  main:
    allow-bean-definition-overriding: true
management:
  metrics:
    web:
      server:
        auto-time-requests: false
logging:
# 你需要存储日志的目录
  file: D:/interest/file/log/interest.log
  level:
    org.springframework.cloud: DEBUG
    com.interest.zuul: DEBUG