
spring:
  application:
      name: interest-blog
  profiles:
    active: dev
---
#dev environment
server:
  port: 8085
  servlet:
    context-path: /interest/blog

spring:
  rabbitmq:
    host: 192.168.17.11
    port: 5672
    username: admin
    password: admin
  sleuth:
    sampler:
      rate: 1
  profiles: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/interest_blog?useUnicode=true&createDatabaseIfNotExist=true&characterEncoding=UTF-8&useSSL=false&jdbcCompliantTruncation=false&serverTimezone=Hongkong
    username: root
    password: 123456a?
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      connection-test-query: SELECT 1
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: DatebookHikariCP
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: null
    timeout: 5000ms
    jedis:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 100000ms
  liquibase:
    change-log: classpath:database/master.xml
    enabled: true
    drop-first: false
  resources:
    static-locations:
      - classpath:/META-INF/resources/
      - classpath:/resources/
      - classpath:/static/
      - classpath:/public/
      - file:${interest.paths-properties.image}
logging:
  # 你需要存储日志的目录
  file: D:/interest/file/log/interest.log
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    com.interest.blog: DEBUG
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.interest.blog.model
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
#自定义配置
interest:
  paths-properties:
    image: D:/interest/file/image
    #    image: 你需要存储图片的目录，如上
    domain-name: http://127.0.0.1:8081
  #   domain-name: https://www.lovemtt.com
  #   domain-name: 你的域名或者（ip+端口），如上
  github:
    client-id: 你在github中注册的client id
    client-secret: 你在github中注册的client secret
  qq:
    appid: 你在qq中注册的appid
    appkey: 你在qq中注册的appkey
---
#prod environment
server:
  port: 8085
  servlet:
    context-path: /interest/blog
eureka:
  client:
    service-url:
      defaultZone: http://192.168.17.10:8761/eureka/
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://192.168.17.1:3306/interest_blog?useUnicode=true&createDatabaseIfNotExist=true&characterEncoding=UTF-8&useSSL=false&jdbcCompliantTruncation=false&serverTimezone=Hongkong
    username: root
    password: 123456a?
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      connection-test-query: SELECT 1
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: DatebookHikariCP
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: null
    timeout: 5000ms
    jedis:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 100000ms
  liquibase:
    change-log: classpath:database/master.xml
    enabled: true
    drop-first: false
  resources:
    static-locations:
    - classpath:/META-INF/resources/
    - classpath:/resources/
    - classpath:/static/
    - classpath:/public/
    - file:${interest.paths-properties.image}
logging:
# 你需要存储日志的目录
  file: blog/file/log/interest.log
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    com.interest.blog: DEBUG
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.interest.blog.model
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
#自定义配置
interest:
  paths-properties:
    image: /blog/file/image
#    image: 你需要存储图片的目录，如上
    domain-name: http://192.168.17.10:8081
#   domain-name: https://www.lovemtt.com
#   domain-name: 你的域名或者（ip+端口），如上
  github:
    client-id: 你在github中注册的client id
    client-secret: 你在github中注册的client secret
  qq:
    appid: 你在qq中注册的appid
    appkey: 你在qq中注册的appkey